New link preview
gambiconf/gambiconf.github.io pull request #27
Opened 2023-08-16 12:02 UTC by grandehe4rt

@macabeus 
Fiz o que tu solicitou ali pra colocar um link preview no app, eu pesquisei como faria isso no svelte e tive esse resultado que ta no código da PR, não consegui testar porque não consegui fazer deploy direito, eu subi num github pages e ficou aparecendo só o readme.

enfim, mas acho que tudo bem visto que são só meta tags, se fizer deploy agora e enviar um link pro discord por exemplo, é bem provável que o preview tenha uma aparência melhorada.

2023-08-16 12:13 UTC, Camilotk requested changes

2023-08-16 12:13 UTC, Camilotk commented on src/routes/+layout.svelte
> +  <meta property="og:description" content="É a gambiconf né dog." />
Aqui precisamos de algo que funcione bem para trazer pessoas através do link, algo como:
> Venha conhecer projetos e ideias incríveis que misturam humor, criatividade e computação. Dias 25 e 26 de Novembro na USP - Campus Butantã. Inscreva-se já!

2023-08-16 12:13 UTC, Camilotk commented on src/routes/+layout.svelte
> +  <!-- <meta name="twitter:card" content="summary_large_image" /> -->
Necessário?

2025-04-30 00:05 UTC, macabeus commented
Staled

2025-04-30 00:05 UTC, closed without merging